---
global:
  gc: true
  measurements:
  - name: pprof
    pprofInterval: 30m
    pprofDirectory: pprof-data
    nodeAffinity:
      kubernetes.io/hostname : "kubebrowse-cluster-worker"
    pprofTargets:
    - name: kubelet-heap
      url: https://localhost:10250/debug/pprof/heap

    # - name: crio-heap
    #   url: unix:///var/run/crio/crio.sock/debug/pprof/heap
jobs:
  - name: kubelet-density
    jobIterations: 25
    qps: 2
    burst: 2
    preLoadImages: false
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:
      - objectTemplate: ./examples/workloads/kubelet-density/templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
